print("Name: Fatima Amin")
print("Father Name: Amin-ul-haq")
print("Age: 19")
print("Gender: Female")
print("Date of Birth: 03-june-2007")
print("Class: BS Psychology")
print("Roll: 434")
print("Semester: Second")
print("Collage Name: FG Degree Collage")
print("Student ID: 104-BSPSY/26-434")
print("Adrees: ASC Colony")
print("City: Nowshera")
print("Country: Pakistan")
print("Postal Code: 4600")
print("Email: fatimaamin0313@gmail.com")
print("Phone Number: 03169530034")
print("Favourit Subject: Psychology")
print("Second Subject: Mathematics")
print("Favourit Teacher: Maam Yousra")
print("Current GPA: 2.71")
print("Attendence perecentage: 95%")
print("Hobby: Reading Books")
print("Favourit Sport: tennes")
print("Favourit Colour: Blue")
print("Favourit Food: Showarma")
print("Favourit Book: Don't Belive Everything You Think")
print("Future Goal: Psychologist")
print("Dream University: NUP")
print("Programming Language: Python")
print("Study Per Day: 4")
print("Best Friend: Maheen")